services:
  db:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U login"]
      interval: 5s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TrialsServerArchive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "2310:2310"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=TrialsServerArchive;Username=login;Password=password
    command: ["sh", "-c", "dotnet TrialsServerArchive.dll"]

volumes:
  postgres_data: